-- On-site Demo packages (PRD #32).
-- The demo cost depends on the area to be demoed, so — exactly like the
-- installation tiers — each area band is a regular product: category
-- 'services', variant 'demo'. The demo product page (DemoPurchasePanel) lets
-- the shopper pick the area band (this price) and which robot model to demo.
-- Demo is intentionally NOT offered in the checkout upsell.
--
-- Run once in Supabase: SQL Editor -> New query -> paste -> Run.
-- Safe to re-run (on conflict updates in place). PRICES BELOW ARE PLACEHOLDERS
-- in whole Thai Baht — change them here before running, or edit in the admin
-- panel afterwards. Re-running overwrites any manual price edits on these ids.

insert into public.products
  (id, name, price, category, variant, images, preorder, visible, specs, tagline, description, features)
values
  ('demo-up-to-1000', 'On-Site Demo — Up to 1,000 m²', 990, 'services', 'demo', '[]'::jsonb, false, true, '{"area":"Up to 1,000 m²"}'::jsonb, '{"en":"A live, on-site demo on lawns up to 1,000 m²","th":"สาธิตการใช้งานจริงถึงบ้าน สำหรับสนามไม่เกิน 1,000 ตร.ม."}'::jsonb, '{"en":"A specialist brings the robot to your property and runs a live demonstration on your own lawn — showing the cut, mapping and setup, and answering your questions. The fee is credited toward your purchase. Covers areas up to 1,000 m².","th":"ผู้เชี่ยวชาญนำหุ่นยนต์ไปสาธิตการใช้งานจริงบนสนามของคุณ ทั้งการตัด การทำแผนที่ และการตั้งค่า พร้อมตอบทุกคำถาม ค่าบริการนำไปเป็นส่วนลดเมื่อซื้อได้ รองรับพื้นที่ไม่เกิน 1,000 ตร.ม."}'::jsonb, '{"en":["Live, on-site demonstration","See it work on your own lawn","Ask a specialist anything","Fee credited toward your purchase"],"th":["สาธิตการใช้งานจริงถึงบ้าน","ดูการทำงานบนสนามของคุณเอง","ปรึกษาผู้เชี่ยวชาญได้ทุกเรื่อง","ค่าบริการใช้เป็นส่วนลดตอนซื้อได้"]}'::jsonb),
  ('demo-up-to-2000', 'On-Site Demo — Up to 2,000 m²', 1490, 'services', 'demo', '[]'::jsonb, false, true, '{"area":"Up to 2,000 m²"}'::jsonb, '{"en":"A live, on-site demo on lawns up to 2,000 m²","th":"สาธิตการใช้งานจริงถึงบ้าน สำหรับสนามไม่เกิน 2,000 ตร.ม."}'::jsonb, '{"en":"A specialist brings the robot to your property and runs a live demonstration on your own lawn — showing the cut, mapping and setup, and answering your questions. The fee is credited toward your purchase. Covers areas up to 2,000 m².","th":"ผู้เชี่ยวชาญนำหุ่นยนต์ไปสาธิตการใช้งานจริงบนสนามของคุณ ทั้งการตัด การทำแผนที่ และการตั้งค่า พร้อมตอบทุกคำถาม ค่าบริการนำไปเป็นส่วนลดเมื่อซื้อได้ รองรับพื้นที่ไม่เกิน 2,000 ตร.ม."}'::jsonb, '{"en":["Live, on-site demonstration","See it work on your own lawn","Ask a specialist anything","Fee credited toward your purchase"],"th":["สาธิตการใช้งานจริงถึงบ้าน","ดูการทำงานบนสนามของคุณเอง","ปรึกษาผู้เชี่ยวชาญได้ทุกเรื่อง","ค่าบริการใช้เป็นส่วนลดตอนซื้อได้"]}'::jsonb),
  ('demo-up-to-3000', 'On-Site Demo — Up to 3,000 m²', 1990, 'services', 'demo', '[]'::jsonb, false, true, '{"area":"Up to 3,000 m²"}'::jsonb, '{"en":"A live, on-site demo on lawns up to 3,000 m²","th":"สาธิตการใช้งานจริงถึงบ้าน สำหรับสนามไม่เกิน 3,000 ตร.ม."}'::jsonb, '{"en":"A specialist brings the robot to your property and runs a live demonstration on your own lawn — showing the cut, mapping and setup, and answering your questions. The fee is credited toward your purchase. Covers areas up to 3,000 m².","th":"ผู้เชี่ยวชาญนำหุ่นยนต์ไปสาธิตการใช้งานจริงบนสนามของคุณ ทั้งการตัด การทำแผนที่ และการตั้งค่า พร้อมตอบทุกคำถาม ค่าบริการนำไปเป็นส่วนลดเมื่อซื้อได้ รองรับพื้นที่ไม่เกิน 3,000 ตร.ม."}'::jsonb, '{"en":["Live, on-site demonstration","See it work on your own lawn","Ask a specialist anything","Fee credited toward your purchase"],"th":["สาธิตการใช้งานจริงถึงบ้าน","ดูการทำงานบนสนามของคุณเอง","ปรึกษาผู้เชี่ยวชาญได้ทุกเรื่อง","ค่าบริการใช้เป็นส่วนลดตอนซื้อได้"]}'::jsonb),
  ('demo-up-to-5000', 'On-Site Demo — Up to 5,000 m²', 2490, 'services', 'demo', '[]'::jsonb, false, true, '{"area":"Up to 5,000 m²"}'::jsonb, '{"en":"A live, on-site demo on lawns up to 5,000 m²","th":"สาธิตการใช้งานจริงถึงบ้าน สำหรับสนามไม่เกิน 5,000 ตร.ม."}'::jsonb, '{"en":"A specialist brings the robot to your property and runs a live demonstration on your own lawn — showing the cut, mapping and setup, and answering your questions. The fee is credited toward your purchase. Covers areas up to 5,000 m².","th":"ผู้เชี่ยวชาญนำหุ่นยนต์ไปสาธิตการใช้งานจริงบนสนามของคุณ ทั้งการตัด การทำแผนที่ และการตั้งค่า พร้อมตอบทุกคำถาม ค่าบริการนำไปเป็นส่วนลดเมื่อซื้อได้ รองรับพื้นที่ไม่เกิน 5,000 ตร.ม."}'::jsonb, '{"en":["Live, on-site demonstration","See it work on your own lawn","Ask a specialist anything","Fee credited toward your purchase"],"th":["สาธิตการใช้งานจริงถึงบ้าน","ดูการทำงานบนสนามของคุณเอง","ปรึกษาผู้เชี่ยวชาญได้ทุกเรื่อง","ค่าบริการใช้เป็นส่วนลดตอนซื้อได้"]}'::jsonb),
  ('demo-up-to-10000', 'On-Site Demo — Up to 10,000 m²', 2990, 'services', 'demo', '[]'::jsonb, false, true, '{"area":"Up to 10,000 m²"}'::jsonb, '{"en":"A live, on-site demo on lawns up to 10,000 m²","th":"สาธิตการใช้งานจริงถึงบ้าน สำหรับสนามไม่เกิน 10,000 ตร.ม."}'::jsonb, '{"en":"A specialist brings the robot to your property and runs a live demonstration on your own lawn — showing the cut, mapping and setup, and answering your questions. The fee is credited toward your purchase. Covers areas up to 10,000 m².","th":"ผู้เชี่ยวชาญนำหุ่นยนต์ไปสาธิตการใช้งานจริงบนสนามของคุณ ทั้งการตัด การทำแผนที่ และการตั้งค่า พร้อมตอบทุกคำถาม ค่าบริการนำไปเป็นส่วนลดเมื่อซื้อได้ รองรับพื้นที่ไม่เกิน 10,000 ตร.ม."}'::jsonb, '{"en":["Live, on-site demonstration","See it work on your own lawn","Ask a specialist anything","Fee credited toward your purchase"],"th":["สาธิตการใช้งานจริงถึงบ้าน","ดูการทำงานบนสนามของคุณเอง","ปรึกษาผู้เชี่ยวชาญได้ทุกเรื่อง","ค่าบริการใช้เป็นส่วนลดตอนซื้อได้"]}'::jsonb)
on conflict (id) do update set
  name = excluded.name, price = excluded.price, category = excluded.category,
  variant = excluded.variant, visible = true, specs = excluded.specs,
  tagline = excluded.tagline, description = excluded.description, features = excluded.features;

-- Retire the old single flat-rate demo so the storefront shows only the
-- area-based tiers above. (No-op if the row was never seeded.)
update public.products set visible = false where id = 'request-a-demo';
