-- Installation Service packages (PRD #11 upsell tiers).
-- Creates/updates the five tiers as regular products: category 'services',
-- variant 'install'. The checkout matches a tier to each robot by specs.area
-- (smallest tier whose area >= the robot's area), so keep the area values.
--
-- Run once in Supabase: SQL Editor -> New query -> paste -> Run.
-- Safe to re-run (on conflict updates in place). PRICES BELOW ARE PLACEHOLDERS
-- in whole Thai Baht — change them here before running, or edit in the admin
-- panel afterwards. Re-running overwrites any manual price edits on these ids.

insert into public.products
  (id, name, price, category, variant, images, preorder, visible, specs, tagline, description, features)
values
  ('install-up-to-1000', 'Installation Service — Up to 1,000 m²', 3500, 'services', 'install', '[]'::jsonb, false, true, '{"area":"Up to 1,000 m²"}'::jsonb, '{"en":"Professional on-site setup for lawns up to 1,000 m²","th":"บริการติดตั้งถึงบ้านโดยช่างมืออาชีพ สำหรับสนามไม่เกิน 1,000 ตร.ม."}'::jsonb, '{"en":"A trained technician installs and configures your robot mower on-site — mapping the lawn, setting boundaries and no-go zones, and confirming a clean cut before handover. Covers properties up to 1,000 m².","th":"ช่างผู้ชำนาญติดตั้งและตั้งค่าหุ่นยนต์ตัดหญ้าให้ถึงบ้าน ทำแผนที่สนาม กำหนดขอบเขตและพื้นที่ห้ามเข้า และทดสอบการตัดจนเรียบร้อยก่อนส่งมอบ รองรับพื้นที่ไม่เกิน 1,000 ตร.ม."}'::jsonb, '{"en":["On-site installation by a trained technician","Lawn mapping & boundary setup","No-go zones & schedule configuration","Test run and handover"],"th":["ติดตั้งถึงบ้านโดยช่างผู้ชำนาญ","ทำแผนที่สนามและกำหนดขอบเขต","ตั้งค่าพื้นที่ห้ามเข้าและตารางการทำงาน","ทดสอบการทำงานและส่งมอบ"]}'::jsonb),
  ('install-up-to-2000', 'Installation Service — Up to 2,000 m²', 5500, 'services', 'install', '[]'::jsonb, false, true, '{"area":"Up to 2,000 m²"}'::jsonb, '{"en":"Professional on-site setup for lawns up to 2,000 m²","th":"บริการติดตั้งถึงบ้านโดยช่างมืออาชีพ สำหรับสนามไม่เกิน 2,000 ตร.ม."}'::jsonb, '{"en":"A trained technician installs and configures your robot mower on-site — mapping the lawn, setting boundaries and no-go zones, and confirming a clean cut before handover. Covers properties up to 2,000 m².","th":"ช่างผู้ชำนาญติดตั้งและตั้งค่าหุ่นยนต์ตัดหญ้าให้ถึงบ้าน ทำแผนที่สนาม กำหนดขอบเขตและพื้นที่ห้ามเข้า และทดสอบการตัดจนเรียบร้อยก่อนส่งมอบ รองรับพื้นที่ไม่เกิน 2,000 ตร.ม."}'::jsonb, '{"en":["On-site installation by a trained technician","Lawn mapping & boundary setup","No-go zones & schedule configuration","Test run and handover"],"th":["ติดตั้งถึงบ้านโดยช่างผู้ชำนาญ","ทำแผนที่สนามและกำหนดขอบเขต","ตั้งค่าพื้นที่ห้ามเข้าและตารางการทำงาน","ทดสอบการทำงานและส่งมอบ"]}'::jsonb),
  ('install-up-to-3000', 'Installation Service — Up to 3,000 m²', 7000, 'services', 'install', '[]'::jsonb, false, true, '{"area":"Up to 3,000 m²"}'::jsonb, '{"en":"Professional on-site setup for lawns up to 3,000 m²","th":"บริการติดตั้งถึงบ้านโดยช่างมืออาชีพ สำหรับสนามไม่เกิน 3,000 ตร.ม."}'::jsonb, '{"en":"A trained technician installs and configures your robot mower on-site — mapping the lawn, setting boundaries and no-go zones, and confirming a clean cut before handover. Covers properties up to 3,000 m².","th":"ช่างผู้ชำนาญติดตั้งและตั้งค่าหุ่นยนต์ตัดหญ้าให้ถึงบ้าน ทำแผนที่สนาม กำหนดขอบเขตและพื้นที่ห้ามเข้า และทดสอบการตัดจนเรียบร้อยก่อนส่งมอบ รองรับพื้นที่ไม่เกิน 3,000 ตร.ม."}'::jsonb, '{"en":["On-site installation by a trained technician","Lawn mapping & boundary setup","No-go zones & schedule configuration","Test run and handover"],"th":["ติดตั้งถึงบ้านโดยช่างผู้ชำนาญ","ทำแผนที่สนามและกำหนดขอบเขต","ตั้งค่าพื้นที่ห้ามเข้าและตารางการทำงาน","ทดสอบการทำงานและส่งมอบ"]}'::jsonb),
  ('install-up-to-5000', 'Installation Service — Up to 5,000 m²', 9000, 'services', 'install', '[]'::jsonb, false, true, '{"area":"Up to 5,000 m²"}'::jsonb, '{"en":"Professional on-site setup for lawns up to 5,000 m²","th":"บริการติดตั้งถึงบ้านโดยช่างมืออาชีพ สำหรับสนามไม่เกิน 5,000 ตร.ม."}'::jsonb, '{"en":"A trained technician installs and configures your robot mower on-site — mapping the lawn, setting boundaries and no-go zones, and confirming a clean cut before handover. Covers properties up to 5,000 m².","th":"ช่างผู้ชำนาญติดตั้งและตั้งค่าหุ่นยนต์ตัดหญ้าให้ถึงบ้าน ทำแผนที่สนาม กำหนดขอบเขตและพื้นที่ห้ามเข้า และทดสอบการตัดจนเรียบร้อยก่อนส่งมอบ รองรับพื้นที่ไม่เกิน 5,000 ตร.ม."}'::jsonb, '{"en":["On-site installation by a trained technician","Lawn mapping & boundary setup","No-go zones & schedule configuration","Test run and handover"],"th":["ติดตั้งถึงบ้านโดยช่างผู้ชำนาญ","ทำแผนที่สนามและกำหนดขอบเขต","ตั้งค่าพื้นที่ห้ามเข้าและตารางการทำงาน","ทดสอบการทำงานและส่งมอบ"]}'::jsonb),
  ('install-up-to-10000', 'Installation Service — Up to 10,000 m²', 12000, 'services', 'install', '[]'::jsonb, false, true, '{"area":"Up to 10,000 m²"}'::jsonb, '{"en":"Professional on-site setup for lawns up to 10,000 m²","th":"บริการติดตั้งถึงบ้านโดยช่างมืออาชีพ สำหรับสนามไม่เกิน 10,000 ตร.ม."}'::jsonb, '{"en":"A trained technician installs and configures your robot mower on-site — mapping the lawn, setting boundaries and no-go zones, and confirming a clean cut before handover. Covers properties up to 10,000 m².","th":"ช่างผู้ชำนาญติดตั้งและตั้งค่าหุ่นยนต์ตัดหญ้าให้ถึงบ้าน ทำแผนที่สนาม กำหนดขอบเขตและพื้นที่ห้ามเข้า และทดสอบการตัดจนเรียบร้อยก่อนส่งมอบ รองรับพื้นที่ไม่เกิน 10,000 ตร.ม."}'::jsonb, '{"en":["On-site installation by a trained technician","Lawn mapping & boundary setup","No-go zones & schedule configuration","Test run and handover"],"th":["ติดตั้งถึงบ้านโดยช่างผู้ชำนาญ","ทำแผนที่สนามและกำหนดขอบเขต","ตั้งค่าพื้นที่ห้ามเข้าและตารางการทำงาน","ทดสอบการทำงานและส่งมอบ"]}'::jsonb)
on conflict (id) do update set
  name = excluded.name, price = excluded.price, category = excluded.category,
  variant = excluded.variant, visible = true, specs = excluded.specs,
  tagline = excluded.tagline, description = excluded.description, features = excluded.features;
