/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    announcement: Announcement;
    about: About;
    contact: Contact;
    seo: Seo;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    announcement: AnnouncementSelect<false> | AnnouncementSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'marketing';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Hero, feature showcase, video gallery and the Who We Are block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Shown very large — keep it short.
   */
  heroHeadline?: {
    en?: string | null;
    th?: string | null;
  };
  /**
   * Optional. Always starts on its own line.
   */
  heroAccent?: {
    en?: string | null;
    th?: string | null;
  };
  heroSub?: {
    en?: string | null;
    th?: string | null;
  };
  /**
   * Played in order, then looped; none shows the animated lawn instead. Upload videos to Cloudinary and put q_auto/ac_none/ right after /upload/ in the link — it compresses the video and drops the sound. A raw phone video will stall on mobile.
   */
  heroVideos?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  featureShowcase?:
    | {
        /**
         * Give each feature its own photo, or the change is not visible.
         */
        image: number | Media;
        heading?: {
          en?: string | null;
          th?: string | null;
        };
        body?: {
          en?: string | null;
          th?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  videoGallery?:
    | {
        /**
         * A YouTube or YouTube Shorts link, or a direct .mp4 link.
         */
        url?: string | null;
        /**
         * Optional. Without it, YouTube videos use their YouTube thumbnail.
         */
        poster?: (number | null) | Media;
        title: string;
        tag?: string | null;
        author?: string | null;
        id?: string | null;
      }[]
    | null;
  trustHeading?: {
    en?: string | null;
    th?: string | null;
  };
  trustBody?: {
    en?: string | null;
    th?: string | null;
  };
  /**
   * Only numbers you can back up if a customer asks. Robots deployed also appears on the About page — keep the two the same.
   */
  trustStats?:
    | {
        value: number;
        decimals?: number | null;
        suffix?: string | null;
        label?: {
          en?: string | null;
          th?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The gold scrolling bar at the top of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement".
 */
export interface Announcement {
  id: number;
  /**
   * Switch off to hide the bar everywhere without deleting the messages.
   */
  enabled?: boolean | null;
  messages?:
    | {
        message?: {
          en?: string | null;
          th?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Everything company-specific on /about. Headings and buttons stay in the site's translation files.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  intro?: {
    en?: string | null;
    th?: string | null;
  };
  /**
   * Shown as typed, e.g. 2021, 1,600+ or 24h. Only numbers you can back up. Empty hides the row.
   */
  stats?:
    | {
        value: string;
        label?: {
          en?: string | null;
          th?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Leave an empty line between paragraphs.
   */
  storyBody?: {
    en?: string | null;
    th?: string | null;
  };
  /**
   * A real photo of the team, showroom or an installation works best.
   */
  storyImage: number | Media;
  partnerEnabled?: boolean | null;
  partnerEyebrow?: {
    en?: string | null;
    th?: string | null;
  };
  partnerName?: string | null;
  /**
   * Words like authorised, official or exclusive are a claim about the partner. Only use one the partner has confirmed in writing, and keep the agreement on file.
   */
  partnerStatus?: {
    en?: string | null;
    th?: string | null;
  };
  partnerBody?: {
    en?: string | null;
    th?: string | null;
  };
  partnerLogo?: (number | null) | Media;
  values?:
    | {
        icon: 'shield' | 'home' | 'wrench' | 'headset';
        title?: {
          en?: string | null;
          th?: string | null;
        };
        body?: {
          en?: string | null;
          th?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  milestones?:
    | {
        when: string;
        title?: {
          en?: string | null;
          th?: string | null;
        };
        body?: {
          en?: string | null;
          th?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  team?:
    | {
        name: string;
        role?: {
          en?: string | null;
          th?: string | null;
        };
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Used in the footer, the contact page, order emails and Google. The company address is not here: it has to match the company registration, so it is changed in code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  phone: string;
  /**
   * Shown to customers. New-order alerts go to the addresses set on the server, not here.
   */
  email: string;
  /**
   * Shown under the phone number. Empty hides it.
   */
  phoneHours?: {
    en?: string | null;
    th?: string | null;
  };
  lineId: string;
  lineUrl?: string | null;
  /**
   * If you change the QR code, change the add-friend link to the same account too.
   */
  lineQrImage?: (number | null) | Media;
  /**
   * Leave a platform empty if there is no account — its icon disappears from the footer.
   */
  socials?: {
    facebook?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * What Google and link previews on LINE and Facebook show for the site and each product.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  siteTitle?: {
    en?: string | null;
    th?: string | null;
  };
  siteDescription?: {
    en?: string | null;
    th?: string | null;
  };
  /**
   * Shown when a page without its own photo is shared on LINE or Facebook. 1200 × 630 works best.
   */
  shareImage: number | Media;
  products?:
    | {
        productId: string;
        title?: {
          en?: string | null;
          th?: string | null;
        };
        description?: {
          en?: string | null;
          th?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroHeadline?:
    | T
    | {
        en?: T;
        th?: T;
      };
  heroAccent?:
    | T
    | {
        en?: T;
        th?: T;
      };
  heroSub?:
    | T
    | {
        en?: T;
        th?: T;
      };
  heroVideos?:
    | T
    | {
        url?: T;
        id?: T;
      };
  featureShowcase?:
    | T
    | {
        image?: T;
        heading?:
          | T
          | {
              en?: T;
              th?: T;
            };
        body?:
          | T
          | {
              en?: T;
              th?: T;
            };
        id?: T;
      };
  videoGallery?:
    | T
    | {
        url?: T;
        poster?: T;
        title?: T;
        tag?: T;
        author?: T;
        id?: T;
      };
  trustHeading?:
    | T
    | {
        en?: T;
        th?: T;
      };
  trustBody?:
    | T
    | {
        en?: T;
        th?: T;
      };
  trustStats?:
    | T
    | {
        value?: T;
        decimals?: T;
        suffix?: T;
        label?:
          | T
          | {
              en?: T;
              th?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement_select".
 */
export interface AnnouncementSelect<T extends boolean = true> {
  enabled?: T;
  messages?:
    | T
    | {
        message?:
          | T
          | {
              en?: T;
              th?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        en?: T;
        th?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?:
          | T
          | {
              en?: T;
              th?: T;
            };
        id?: T;
      };
  storyBody?:
    | T
    | {
        en?: T;
        th?: T;
      };
  storyImage?: T;
  partnerEnabled?: T;
  partnerEyebrow?:
    | T
    | {
        en?: T;
        th?: T;
      };
  partnerName?: T;
  partnerStatus?:
    | T
    | {
        en?: T;
        th?: T;
      };
  partnerBody?:
    | T
    | {
        en?: T;
        th?: T;
      };
  partnerLogo?: T;
  values?:
    | T
    | {
        icon?: T;
        title?:
          | T
          | {
              en?: T;
              th?: T;
            };
        body?:
          | T
          | {
              en?: T;
              th?: T;
            };
        id?: T;
      };
  milestones?:
    | T
    | {
        when?: T;
        title?:
          | T
          | {
              en?: T;
              th?: T;
            };
        body?:
          | T
          | {
              en?: T;
              th?: T;
            };
        id?: T;
      };
  team?:
    | T
    | {
        name?: T;
        role?:
          | T
          | {
              en?: T;
              th?: T;
            };
        photo?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  phoneHours?:
    | T
    | {
        en?: T;
        th?: T;
      };
  lineId?: T;
  lineUrl?: T;
  lineQrImage?: T;
  socials?:
    | T
    | {
        facebook?: T;
        youtube?: T;
        tiktok?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  siteTitle?:
    | T
    | {
        en?: T;
        th?: T;
      };
  siteDescription?:
    | T
    | {
        en?: T;
        th?: T;
      };
  shareImage?: T;
  products?:
    | T
    | {
        productId?: T;
        title?:
          | T
          | {
              en?: T;
              th?: T;
            };
        description?:
          | T
          | {
              en?: T;
              th?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}