import { Resend } from "resend";
import { siteConfig } from "@/data/siteConfig";

/**
 * Outbound application email (order confirmations, sales alerts).
 *
 * This is a SEPARATE path from the auth emails: signup confirmation and
 * password reset are generated by Supabase and handed to Resend over SMTP.
 * These are generated by us and handed to Resend over its HTTP API. Same
 * account, same verified domain, same free tier.
 *
 * Everything here degrades to a no-op when RESEND_API_KEY is unset, matching
 * how lib/omise.ts behaves without its keys: the storefront keeps working and
 * you simply don't get email until the key is configured.
 */

/** Verified sending domain — see supabase/../DNS notes; must match Resend. */
const FROM = process.env.EMAIL_FROM ?? "FindMyRobo <noreply@send.findmyrobo.com>";

/**
 * Where new-order alerts go. Comma-separate SALES_ALERT_EMAIL for several
 * people — changing who is notified is then an env var edit, not a deploy.
 *
 *   SALES_ALERT_EMAIL=sales@raaspal.com, chris@raaspal.com, ops@raaspal.com
 *
 * All recipients are on `to` rather than bcc: this is an internal alert, and
 * the team seeing who else was notified is useful, not a leak.
 */
export const salesAlertRecipients = (
  process.env.SALES_ALERT_EMAIL ?? siteConfig.salesContact.email
)
  .split(",")
  .map((address) => address.trim())
  .filter(Boolean);

/** First recipient — used as the customer-facing Reply-To. */
export const salesReplyTo = salesAlertRecipients[0] ?? siteConfig.salesContact.email;

export const emailConfigured = Boolean(process.env.RESEND_API_KEY);

let client: Resend | null = null;
function getClient(): Resend | null {
  if (!process.env.RESEND_API_KEY) return null;
  client ??= new Resend(process.env.RESEND_API_KEY);
  return client;
}

export interface SendArgs {
  to: string | string[];
  subject: string;
  html: string;
  replyTo?: string;
}

/**
 * Sends one email. NEVER throws.
 *
 * Callers are order flows: a customer who has just paid must not see an error
 * because our mail provider had a bad minute. Failures are logged and
 * swallowed; the order itself is already safely in the database.
 */
export async function sendEmail(args: SendArgs): Promise<boolean> {
  const resend = getClient();
  if (!resend) {
    console.warn(
      `[email] RESEND_API_KEY not set — skipped "${args.subject}" to ${String(args.to)}`
    );
    return false;
  }

  try {
    const { error } = await resend.emails.send({
      from: FROM,
      to: Array.isArray(args.to) ? args.to : [args.to],
      subject: args.subject,
      html: args.html,
      ...(args.replyTo ? { replyTo: args.replyTo } : {}),
    });
    if (error) {
      console.error(`[email] send failed for "${args.subject}":`, error);
      return false;
    }
    return true;
  } catch (cause) {
    console.error(`[email] threw for "${args.subject}":`, cause);
    return false;
  }
}
