/**
 * RETURN, EXCHANGE, CLAIM & REFUND POLICY — the published legal text.
 *
 * ⚠️ TRANSCRIBED VERBATIM, generated by script, from the company's documents:
 *    th: docs/policy/RAASPAL_Return_Exchange_Claim_Refund_Policy_TH_Revised-2.docx
 *    en: docs/policy/RAASPAL_Return_Exchange_Claim_Refund_Policy_EN.docx
 *
 * These are binding commitments to customers, not marketing copy. Do not
 * reword, summarise, shorten, or "improve" any line. If the policy changes,
 * regenerate this file from the new documents — never edit a sentence in
 * place, and never edit one language without the other: the two versions
 * have the same ten sections line for line, and a customer comparing them
 * must find the same terms.
 *
 * NOTE: the phone number in section 3 is part of the documents. It currently
 * matches siteConfig.salesContact.phone — keep them in step.
 */

import type { Locale } from "@/data/products";

export type PolicyBlock =
  | { type: "p"; text: string }
  /** A titled passage inside a section, e.g. the unboxing-video guidance in §1. */
  | { type: "subheading"; text: string }
  /** Items keep their own numbering from the document — "1.1", "(2)" — so the
   *  page renders them without a list marker. */
  | { type: "list"; items: string[] }
  /** A contact line, rendered highlighted rather than as body text. */
  | { type: "contact"; text: string };

export interface PolicySection {
  heading: string;
  body: PolicyBlock[];
}

export interface PolicyDocument {
  title: string;
  intro: string;
  sections: PolicySection[];
}

export const returnPolicy: Record<Locale, PolicyDocument> = {
  th: {
    title: "นโยบายการเปลี่ยน คืน เคลมสินค้า และการคืนเงิน",
    intro: "บริษัท ราส พอล จำกัด (“บริษัทฯ”) ให้ความสำคัญกับคุณภาพสินค้า การบริการ และสิทธิของลูกค้า จึงกำหนดนโยบายการเปลี่ยน คืน เคลมสินค้า และการคืนเงิน สำหรับสินค้าที่สั่งซื้อผ่านช่องทางออนไลน์ของบริษัทฯ ภายใต้เงื่อนไขดังต่อไปนี้",
    sections: [
      {
        heading: "1. กรณีที่ลูกค้าสามารถขอเปลี่ยน คืน หรือเคลมสินค้าได้",
        body: [
          {
            type: "list",
            items: [
              "1.1 ได้รับสินค้าไม่ตรงตามคำสั่งซื้อ เช่น ผิดรุ่น ผิดประเภท หรือผิดจำนวน",
              "1.2 สินค้ามีข้อบกพร่องหรือชำรุดอันเกิดจากการผลิต",
              "1.3 สินค้าเสียหายระหว่างการจัดส่ง โดยลูกค้าควรจัดเตรียมหลักฐานประกอบ เช่น ภาพถ่ายหรือวิดีโอ",
              "1.4 สินค้าหรืออุปกรณ์ที่ได้รับมีชิ้นส่วนไม่ครบถ้วน",
              "1.5 วัสดุสิ้นเปลืองที่ได้รับหมดอายุ ณ วันที่ได้รับสินค้า",
              "1.6 สินค้าไม่สามารถใช้งานได้ตามคุณสมบัติที่ระบุ อันเนื่องมาจากข้อบกพร่องของตัวสินค้า",
              "1.7 ความเสียหายหรือปัญหาที่เกิดจากการติดตั้งโดยบริษัทฯ",
            ],
          },
          { type: "p", text: "ระยะเวลาแจ้งคำขอ: ลูกค้าต้องแจ้งคำขอภายใน 7 วันนับจากวันที่ได้รับสินค้า พร้อมหลักฐานการสั่งซื้อและหลักฐานประกอบ" },
          { type: "p", text: "ทั้งนี้ ความชำรุดบกพร่องของสินค้าที่ตรวจพบภายหลังพ้นระยะเวลาดังกล่าว ลูกค้ายังคงสามารถใช้สิทธิตามเงื่อนไขการรับประกันของสินค้าแต่ละประเภทได้" },
          { type: "subheading", text: "การถ่ายวิดีโอขณะเปิดกล่องสินค้า (Unboxing)" },
          { type: "p", text: "เพื่อประโยชน์ของลูกค้าในการขอเปลี่ยน คืน หรือเคลมสินค้า บริษัทฯ ขอความร่วมมือลูกค้าถ่ายวิดีโอต่อเนื่องตั้งแต่ก่อนเปิดกล่องสินค้า โดยให้เห็น" },
          {
            type: "list",
            items: [
              "(1) สภาพหีบห่อภายนอกและป้ายจัดส่ง",
              "(2) ขั้นตอนการเปิดกล่อง",
              "(3) สภาพสินค้าและอุปกรณ์ภายในกล่อง",
            ],
          },
          { type: "p", text: "วิดีโอดังกล่าวจะช่วยให้บริษัทฯ ตรวจสอบและอนุมัติคำขอได้รวดเร็วยิ่งขึ้น โดยเฉพาะกรณีสินค้าเสียหายระหว่างการจัดส่งตามข้อ 1.3 และกรณีชิ้นส่วนไม่ครบถ้วนตามข้อ 1.4 ซึ่งบริษัทฯ จำเป็นต้องใช้เป็นหลักฐานประกอบการเรียกร้องกับผู้ให้บริการขนส่ง" },
          { type: "p", text: "ในกรณีที่ลูกค้าไม่ได้ถ่ายวิดีโอขณะเปิดกล่อง บริษัทฯ จะพิจารณาจากหลักฐานอื่นประกอบ เช่น ภาพถ่ายหีบห่อ สภาพสินค้า และรายงานจากผู้ให้บริการขนส่ง ซึ่งอาจใช้ระยะเวลาในการตรวจสอบนานขึ้น และในบางกรณีหลักฐานอาจไม่เพียงพอต่อการอนุมัติคำขอ" },
        ],
      },
      {
        heading: "2. กรณีที่ลูกค้าไม่สามารถเปลี่ยนหรือคืนสินค้าได้",
        body: [
          {
            type: "list",
            items: [
              "2.1 สินค้าเสียหายจากการใช้งานผิดวิธี การติดตั้ง ดัดแปลง หรือซ่อมแซมโดยลูกค้าหรือบุคคลภายนอกที่ไม่ได้รับอนุญาตจากบริษัทฯ",
              "2.2 สินค้าถูกใช้งานเกินกว่าที่จำเป็นและบริษัทฯ ได้ทำการตรวจสอบสภาพของสินค้า แล้วพบว่าไม่มีข้อบกพร่องจากตัวสินค้า",
              "2.3 สินค้าที่สั่งผลิต ดัดแปลง หรือกำหนดคุณสมบัติเป็นพิเศษตามความต้องการของลูกค้า (Customized / Made-to-Order) เว้นแต่สินค้ามีข้อบกพร่องหรือไม่ตรงตามรายละเอียดที่ตกลงไว้",
              "2.4 สินค้าที่ลูกค้าไม่สามารถแสดงหลักฐานการสั่งซื้อจากบริษัทฯ ได้",
              "2.5 สินค้าที่เกิดความเสียหายจากอุบัติเหตุ ภัยธรรมชาติ การใช้งานผิดประเภท ของเหลว หรือปัจจัยภายนอกที่ไม่ได้เกิดจากข้อบกพร่องของสินค้า รวมทั้งความเสียหายที่เกิดจากสัตว์หรือแมลง เป็นต้น",
            ],
          },
          { type: "p", text: "สินค้าลดราคาหรือสินค้าส่งเสริมการขาย ยังสามารถขอเปลี่ยนหรือเคลมได้ หากสินค้าไม่ตรงตามคำสั่งซื้อ มีข้อบกพร่อง และเข้าเงื่อนไขตามข้อ 1" },
        ],
      },
      {
        heading: "3. ขั้นตอนการแจ้งเปลี่ยน คืน หรือเคลมสินค้า",
        body: [
          { type: "p", text: "ลูกค้าต้องติดต่อ Customer Service ของบริษัทฯ ก่อนส่งสินค้าคืนทุกครั้ง ผ่านช่องทางที่บริษัทฯ กำหนด พร้อมแจ้งหมายเลขคำสั่งซื้อ รายละเอียดปัญหา และหลักฐานประกอบ" },
          { type: "contact", text: "โทรศัพท์: 02-576-5555" },
          { type: "p", text: "เมื่อบริษัทฯได้รับข้อมูลครบถ้วนแล้ว บริษัทฯ จะตรวจสอบคำขอและแจ้งผล รวมถึงขั้นตอนการส่งคืน การเข้ารับสินค้า การเปลี่ยนสินค้า การซ่อม หรือการคืนเงินตามความเหมาะสม" },
          { type: "p", text: "หากลูกค้ามิได้ปฏิบัติตามขั้นตอนที่กำหนด บริษัทฯ ไม่อาจสามารถพิจารณาคำขอได้ ทั้งนี้ไม่กระทบสิทธิของผู้บริโภคตามกฎหมายที่ใช้บังคับ" },
        ],
      },
      {
        heading: "4. สภาพสินค้าที่ส่งคืน",
        body: [
          { type: "p", text: "สินค้าที่ส่งคืนบริษัทฯ ควรอยู่ในสภาพสมบูรณ์ พร้อมบรรจุภัณฑ์ คู่มือ ใบรับประกัน อุปกรณ์ และของแถมที่ได้รับพร้อมสินค้า" },
          { type: "p", text: "อย่างไรก็ตาม หากการคืนสินค้าเกิดจากสินค้าชำรุด มีข้อบกพร่อง ได้รับสินค้าไม่ถูกต้อง หรือความเสียหายที่ไม่ได้เกิดจากลูกค้า บริษัทฯ จะพิจารณาตามสภาพและข้อเท็จจริงของสินค้าเป็นรายกรณี" },
        ],
      },
      {
        heading: "5. การตรวจสอบและการดำเนินการ",
        body: [
          { type: "p", text: "ภายหลังจากบริษัทฯได้รับคืนสินค้าและข้อมูลที่เกี่ยวข้อง บริษัทฯ จะดำเนินการตรวจสอบสินค้าและแจ้งผลให้ลูกค้าทราบ" },
          { type: "p", text: "หากคำขอเป็นไปตามเงื่อนไข บริษัทฯ อาจดำเนินการอย่างใดอย่างหนึ่งตามความเหมาะสม ได้แก่ การซ่อมแซม การเปลี่ยนสินค้า การเปลี่ยนเป็นสินค้ารุ่นเทียบเท่า หรือการคืนเงิน โดยพิจารณาจากลักษณะของปัญหา ความพร้อมของสินค้า เงื่อนไขการรับประกัน และข้อตกลงกับลูกค้า" },
          { type: "p", text: "บริษัทฯ จะดำเนินการซ่อมแซม เปลี่ยนสินค้า หรือจัดส่งสินค้าทดแทน ในเวลาไม่เกิน 30 วันทำการ นับจากวันที่บริษัทฯ ได้รับข้อมูลและ/หรือสินค้าที่จำเป็นครบถ้วน และอนุมัติคำขอเรียบร้อยแล้ว" },
          { type: "p", text: "ในกรณีที่ต้องสั่งอะไหล่หรือสินค้าจากผู้ผลิตในต่างประเทศ ซึ่งอาจใช้ระยะเวลาเกินกว่าที่กำหนด บริษัทฯ จะแจ้งกำหนดการโดยประมาณให้ลูกค้าทราบล่วงหน้า" },
        ],
      },
      {
        heading: "6. ค่าใช้จ่ายในการส่งคืนสินค้า",
        body: [
          { type: "p", text: "กรณีที่การคืนหรือเปลี่ยนสินค้าเกิดจากสินค้าไม่ตรงคำสั่งซื้อ สินค้ามีข้อบกพร่อง สินค้าเสียหายจากการจัดส่ง หรือความผิดพลาดของบริษัทฯ บริษัทฯ จะรับผิดชอบค่าใช้จ่ายในการจัดส่งคืนและการจัดส่งสินค้าทดแทนตามวิธีการที่บริษัทฯ กำหนด" },
          { type: "p", text: "กรณีการคืนสินค้าที่ไม่ได้เกิดจากข้อบกพร่องของสินค้า หรือความผิดพลาดของบริษัทฯ และบริษัทฯ พิจารณาอนุมัติเป็นกรณีพิเศษ ลูกค้าอาจเป็นผู้รับผิดชอบค่าขนส่งหรือค่าใช้จ่ายอื่นที่เกิดขึ้น โดยบริษัทฯ จะแจ้งให้ลูกค้าทราบก่อนดำเนินการ" },
        ],
      },
      {
        heading: "7. การคืนเงิน",
        body: [
          { type: "p", text: "กรณีที่บริษัทฯ อนุมัติการคืนเงิน บริษัทฯ จะดำเนินการคืนเงินตามช่องทางที่บริษัทฯ กำหนด เช่น การโอนเงินเข้าบัญชีธนาคารของลูกค้า หรือช่องทางการชำระเงินเดิม หากระบบรองรับ" },
          { type: "p", text: "บริษัทฯ จะดำเนินการคืนเงินในเวลาไม่เกิน 30 วันทำการ นับจากวันที่บริษัทฯ ตรวจสอบและอนุมัติคำขอเรียบร้อยแล้ว ทั้งนี้ ระยะเวลาที่เงินเข้าบัญชีอาจแตกต่างกันตามที่ธนาคารหรือผู้ให้บริการการชำระเงินกำหนด" },
        ],
      },
      {
        heading: "8. การยกเลิกคำสั่งซื้อ",
        body: [
          { type: "p", text: "ลูกค้าสามารถขอยกเลิกคำสั่งซื้อได้ก่อนที่สินค้าจะเข้าสู่กระบวนการจัดส่ง การติดตั้ง การผลิต หรือการดำเนินการตามคำสั่งซื้อเฉพาะของลูกค้า โดยต้องติดต่อ Customer Service ผ่านช่องทางที่บริษัทฯ กำหนด" },
          { type: "p", text: "สำหรับสินค้า Customized / Made-to-Order หรือสินค้าที่บริษัทฯ ได้เริ่มจัดหา ผลิต ดัดแปลง หรือติดตั้งตามคำสั่งซื้อแล้ว การยกเลิกอาจมีค่าใช้จ่ายตามต้นทุนที่เกิดขึ้นจริง โดยบริษัทฯ จะแจ้งเงื่อนไขให้ลูกค้าทราบก่อนดำเนินการ ทั้งนี้ ต้องไม่เป็นการจำกัดสิทธิของผู้บริโภคตามกฎหมายที่ใช้บังคับ" },
        ],
      },
      {
        heading: "9. ค่าใช้จ่ายที่ไม่สามารถขอคืนได้",
        body: [
          { type: "p", text: "ค่าติดตั้ง ค่าบริการ ค่าบรรจุภัณฑ์พิเศษ หรือค่าใช้จ่ายอื่นที่ได้ดำเนินการเสร็จสิ้นแล้ว ลูกค้าไม่สามารถขอคืนได้ เว้นแต่สาเหตุของการขอคืนเกิดจากความผิดพลาดของบริษัทฯ บริการไม่เป็นไปตามข้อตกลง หรือกรณีที่กฎหมายกำหนดให้ลูกค้ามีสิทธิได้รับคืน" },
        ],
      },
      {
        heading: "10. เงื่อนไขทั่วไป",
        body: [
          { type: "p", text: "นโยบายนี้ใช้ควบคู่กับเงื่อนไขการรับประกันของสินค้าแต่ละประเภท รวมถึงข้อกำหนดของผู้ผลิตที่เกี่ยวข้อง โดยข้อกำหนดของผู้ผลิตจะใช้ได้เท่าที่ไม่ขัดต่อสิทธิของลูกค้าตามกฎหมายที่ใช้บังคับ" },
          { type: "p", text: "ในกรณีที่เงื่อนไขใดในนโยบายนี้ขัดหรือแย้งกับสิทธิของผู้บริโภคตามกฎหมายที่ใช้บังคับ ให้สิทธิของผู้บริโภคตามกฎหมายดังกล่าวมีผลเหนือกว่า" },
          { type: "p", text: "บริษัทฯ ขอสงวนสิทธิ์ในการปรับปรุงนโยบายนี้ตามความเหมาะสม โดยการเปลี่ยนแปลงจะไม่มีผลกระทบต่อสิทธิที่เกิดขึ้นจากคำสั่งซื้อที่ดำเนินการก่อนวันที่นโยบายฉบับแก้ไขมีผลใช้บังคับ" },
        ],
      },
    ],
  },
  en: {
    title: "Return, Exchange, Claim & Refund Policy",
    intro: "RAASPAL Co., Ltd. (the \"Company\") places importance on product quality, service, and the rights of its customers. The Company has therefore established this Return, Exchange, Claim and Refund Policy for products ordered through the Company's online channels, subject to the following terms and conditions.",
    sections: [
      {
        heading: "1. Cases in Which the Customer May Request a Return, Exchange or Claim",
        body: [
          {
            type: "list",
            items: [
              "1.1 The product received does not match the order, for example the wrong model, the wrong type, or the wrong quantity.",
              "1.2 The product has a defect or damage arising from the manufacturing process.",
              "1.3 The product was damaged during delivery, in which case the customer should prepare supporting evidence such as photographs or video.",
              "1.4 The product or equipment received has missing parts.",
              "1.5 Consumable materials received have expired as at the date of receipt of the product.",
              "1.6 The product cannot be used in accordance with its specified features, due to a defect in the product itself.",
              "1.7 Damage or problems arising from installation carried out by the Company.",
            ],
          },
          { type: "p", text: "Period for Submitting a Request: The customer must submit a request within 7 days from the date of receipt of the product, together with proof of purchase and supporting evidence." },
          { type: "p", text: "Where a defect in the product is discovered after the expiry of the above period, the customer remains entitled to exercise their rights under the warranty conditions applicable to each type of product." },
          { type: "subheading", text: "Recording a Video While Unboxing the Product (Unboxing)" },
          { type: "p", text: "For the customer's own benefit in requesting a return, exchange or claim, the Company requests the customer's cooperation in recording a continuous video starting before the product box is opened, showing:" },
          {
            type: "list",
            items: [
              "(1) the condition of the outer packaging and the shipping label;",
              "(2) the process of opening the box;",
              "(3) the condition of the product and the equipment inside the box.",
            ],
          },
          { type: "p", text: "Such video will enable the Company to verify and approve the request more quickly, particularly in the case of damage during delivery under Clause 1.3 and missing parts under Clause 1.4, which the Company is required to use as supporting evidence for a claim against the delivery service provider." },
          { type: "p", text: "Where the customer has not recorded a video while unboxing, the Company will consider other supporting evidence, such as photographs of the packaging, the condition of the product, and the report of the delivery service provider. This may require a longer period of verification, and in some cases the evidence may be insufficient for the request to be approved." },
        ],
      },
      {
        heading: "2. Cases in Which the Customer May Not Return or Exchange the Product",
        body: [
          {
            type: "list",
            items: [
              "2.1 The product is damaged as a result of improper use, installation, modification or repair by the customer or by a third party not authorised by the Company.",
              "2.2 The product has been used beyond what is necessary and the Company, having inspected the condition of the product, finds no defect in the product itself.",
              "2.3 Products made to order, modified, or specified with special features at the customer's request (Customized / Made-to-Order), unless the product is defective or does not conform to the agreed specifications.",
              "2.4 Products for which the customer is unable to produce evidence of purchase from the Company.",
              "2.5 Products damaged by accident, natural disaster, use for an improper purpose, liquids, or external factors not arising from a defect in the product, including damage caused by animals or insects, and the like.",
            ],
          },
          { type: "p", text: "Discounted or Promotional Products may still be exchanged or claimed if the product does not match the order or is defective, and falls within the conditions under Clause 1." },
        ],
      },
      {
        heading: "3. Procedure for Notifying a Return, Exchange or Claim",
        body: [
          { type: "p", text: "The customer must contact the Company's Customer Service before returning any product on every occasion, through the channels designated by the Company, stating the order number, details of the problem, and supporting evidence." },
          { type: "contact", text: "Telephone: 02-576-5555" },
          { type: "p", text: "Once the Company has received complete information, the Company will verify the request and notify the customer of the outcome, together with the procedure for return, collection of the product, exchange of the product, repair, or refund, as appropriate." },
          { type: "p", text: "If the customer does not comply with the prescribed procedure, the Company may be unable to consider the request. This does not affect the rights of consumers under applicable law." },
        ],
      },
      {
        heading: "4. Condition of Returned Products",
        body: [
          { type: "p", text: "Products returned to the Company should be in complete condition, together with the packaging, manual, warranty card, accessories, and complimentary items received with the product." },
          { type: "p", text: "However, where the return arises from a product that is damaged or defective, from an incorrect product having been received, or from damage not caused by the customer, the Company will consider the matter on a case-by-case basis according to the condition and the facts relating to the product." },
        ],
      },
      {
        heading: "5. Verification and Action",
        body: [
          { type: "p", text: "After the Company has received the returned product and the relevant information, the Company will inspect the product and notify the customer of the outcome." },
          { type: "p", text: "If the request satisfies the conditions, the Company may take any one of the following actions as appropriate: repair, replacement of the product, replacement with a product of an equivalent model, or a refund, having regard to the nature of the problem, the availability of the product, the warranty conditions, and the agreement with the customer." },
          { type: "p", text: "The Company will carry out the repair, the exchange of the product, or the delivery of a replacement product within a period not exceeding 30 business days from the date on which the Company has received all necessary information and/or products and has duly approved the request." },
          { type: "p", text: "In the event that parts or products must be ordered from a manufacturer overseas, which may take longer than the period specified, the Company will notify the customer of the estimated schedule in advance." },
        ],
      },
      {
        heading: "6. Costs of Returning Products",
        body: [
          { type: "p", text: "Where the return or exchange arises from a product not matching the order, a defect in the product, damage to the product during delivery, or an error on the part of the Company, the Company will be responsible for the costs of return delivery and of delivering the replacement product, by the method designated by the Company." },
          { type: "p", text: "Where the return does not arise from a defect in the product or an error on the part of the Company, and the Company approves it as a special case, the customer may be responsible for the delivery costs or other expenses incurred. The Company will notify the customer before proceeding." },
        ],
      },
      {
        heading: "7. Refunds",
        body: [
          { type: "p", text: "Where the Company approves a refund, the Company will make the refund through the channel designated by the Company, such as a transfer to the customer's bank account or the original payment channel, if supported by the system." },
          { type: "p", text: "The Company will make the refund within a period not exceeding 30 business days from the date on which the Company has duly completed its verification and approved the request. The period for the funds to be credited to the account may vary according to the terms of the bank or the payment service provider." },
        ],
      },
      {
        heading: "8. Cancellation of Orders",
        body: [
          { type: "p", text: "The customer may request to cancel an order before the product enters the process of delivery, installation, production, or fulfilment of the customer's specific order, by contacting Customer Service through the channels designated by the Company." },
          { type: "p", text: "For Customized / Made-to-Order products, or products in respect of which the Company has already commenced procurement, production, modification or installation pursuant to the order, cancellation may incur charges based on the costs actually incurred. The Company will notify the customer of the conditions before proceeding. This shall not operate to limit the rights of consumers under applicable law." },
        ],
      },
      {
        heading: "9. Non-Refundable Costs",
        body: [
          { type: "p", text: "Installation fees, service fees, special packaging fees, or other expenses in respect of work already completed are not refundable to the customer, unless the ground for the refund request arises from an error on the part of the Company, from services not being provided in accordance with the agreement, or from a case in which the law entitles the customer to a refund." },
        ],
      },
      {
        heading: "10. General Conditions",
        body: [
          { type: "p", text: "This Policy applies in conjunction with the warranty conditions of each type of product, as well as the relevant terms of the manufacturer, provided that the manufacturer's terms shall apply only to the extent that they do not conflict with the rights of the customer under applicable law." },
          { type: "p", text: "In the event that any condition in this Policy conflicts with or contradicts the rights of consumers under applicable law, the rights of consumers under such law shall prevail." },
          { type: "p", text: "The Company reserves the right to amend this Policy as appropriate, provided that such amendment shall not affect rights arising from orders placed before the date on which the amended Policy comes into force." },
        ],
      },
    ],
  },
};
